# Generated by Django 4.2.4 on 2023-08-21 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.TextField()),
                ('code', models.TextField()),
                ('link', models.TextField()),
                ('my_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.session')),
            ],
        ),
        migrations.CreateModel(
            name='Main_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gr', models.BooleanField(default=False)),
                ('is_cr', models.BooleanField(default=False)),
                ('my_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.session')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
