# Generated by Django 4.2.4 on 2023-08-21 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('my_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.session')),
            ],
        ),
    ]
