# Generated by Django 4.2.4 on 2023-08-21 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 22, 13, 37, 666841)),
        ),
    ]
