# Generated by Django 4.2.4 on 2023-08-21 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_notification_created_on_evaluation_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 22, 21, 30, 812164)),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 22, 21, 30, 812164)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 22, 21, 30, 812164)),
        ),
    ]
