# Generated by Django 4.2.4 on 2023-08-26 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_evaluation_code_remove_evaluation_sub_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='code',
        ),
        migrations.RemoveField(
            model_name='deadline',
            name='sub_name',
        ),
        migrations.AddField(
            model_name='deadline',
            name='my_slide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.slides'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 14, 31, 59, 29141)),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 14, 31, 59, 29141)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 14, 31, 59, 28144)),
        ),
    ]
