# Generated by Django 4.2.4 on 2023-08-26 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_deadline_code_remove_deadline_sub_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 14, 33, 43, 908591)),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 14, 33, 43, 909588)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 14, 33, 43, 906595)),
        ),
    ]
