# Generated by Django 4.2.4 on 2023-08-26 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_evaluation_end_date_alter_deadline_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_user',
            name='roll_no',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deadline',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 21, 22, 30, 901169)),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 21, 22, 30, 901169)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 21, 22, 30, 900171)),
        ),
    ]
