# Generated by Django 4.2.4 on 2023-08-27 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_main_user_roll_no_alter_deadline_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 19, 40, 6, 142196)),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 19, 40, 6, 143193)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 19, 40, 6, 142196)),
        ),
    ]
