# Generated by Django 4.2.4 on 2023-08-27 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_deadline_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 19, 42, 20, 640187)),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='my_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.session'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='my_slide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.slides'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 19, 42, 20, 641188)),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='my_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.session'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='my_slide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.slides'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 19, 42, 20, 639189)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='my_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.session'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='my_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.session'),
        ),
    ]
